"use client";
import { motion, useScroll, useTransform } from "framer-motion";
import Image from "next/image";
import Link from "next/link";
import { useRef } from "react";

const items = [
  {
    id: 1,
    color: "from-red-300 to-blue-300",
    title: "SportsInn",
    desc: " Developed full-stack sports community platform with real-time notifications and user engagement features Implemented role-based authentication and authorization for secure access control across different user types.",
    img: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8c3BvcnRzfGVufDB8fDB8fHww",
    link: "https://sportsinn.co/login",
  },
  {
    id: 2,
    color: "from-blue-300 to-violet-300",
    title: "E-sanghran",
    desc: "Designed and implemented a user-friendly interface for registering e-waste items, improving accessibility and ease of use. Promoted sustainable e-waste management through digital solutions",
    img: "https://images.unsplash.com/photo-1612965110667-4175024b0dcc?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZXdhc3RlfGVufDB8fDB8fHww",
    link: "https://e-sangrahan.netlify.app/",
  },
  {
    id: 3,
    color: "from-violet-300 to-purple-300",
    title: "Timeboxed",
    desc: "Developed a productivity app using React Native that restricts app and website usage through NFC tag taps scanning for physical session control.implemented timer-based blocking, customizable profiles, and hybrid restriction strategies to enhance fo-cused work habits.Built habit tracking and real-time session monitoring with focus streak analytics, smart breaks, and secure physical unblock mechanisms..",
    img: "https://images.pexels.com/photos/6894528/pexels-photo-6894528.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    link: "https://www.tymeboxed.app/",
  },
  {
    id: 4,
    color: "from-purple-300 to-red-300",
    title: "SpecForge",
    desc: "AI-powered product spec generator. Describe your product or feature, and get user stories, a task board, and risks—generated by Groq's Llama or template fallback. ",
    img: "https://images.pexels.com/photos/18540208/pexels-photo-18540208/free-photo-of-wood-landscape-water-hill.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    link: "https://spec-forge-frontend.vercel.app/login",
  },
];

const PortfolioPage = () => {
  const ref = useRef();

  const { scrollYProgress } = useScroll({ target: ref });
  const x = useTransform(scrollYProgress, [0, 1], ["0%", "-80%"]);

  return (
    <motion.div
      className="h-full"
      initial={{ y: "-200vh" }}
      animate={{ y: "0%" }}
      transition={{ duration: 1 }}
    >
      <div className="h-[600vh] relative" ref={ref}>
        <div className="w-screen h-[calc(100vh-6rem)] flex items-center justify-center text-8xl text-center">
          My Works
        </div>
        <div className="sticky top-0 flex h-[calc(100vh-6rem)] gap-4 items-center overflow-hidden">
          <motion.div style={{ x }} className="flex">
            <div className="h-[calc(100vh-6rem)] min-h-[calc(100vh-6rem)] w-screen flex items-center justify-center bg-gradient-to-r from-purple-300 to-red-300" />
            {items.map((item) => (
              <div
                className={`h-[calc(100vh-6rem)] min-h-[calc(100vh-6rem)] w-screen flex items-center justify-center bg-gradient-to-r ${item.color} px-4 sm:px-6 md:px-8 overflow-y-auto`}
                key={item.id}
              >
                <div className="flex flex-col gap-4 sm:gap-5 md:gap-6 py-6 sm:py-8 text-white max-w-[600px]">
                  <h1 className="text-2xl font-bold sm:text-3xl md:text-4xl lg:text-5xl xl:text-6xl shrink-0">
                    {item.title}
                  </h1>
                  <motion.div
                    className="relative w-full max-w-[520px] aspect-[16/10] shrink-0 rounded-2xl overflow-hidden shadow-2xl ring-2 ring-white/30 mx-auto"
                    whileHover={{ scale: 1.02, boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.25)" }}
                  >
                    <Image src={item.img} alt="" fill className="object-cover" />
                  </motion.div>
                  <div className="rounded-xl bg-white/10 backdrop-blur-md px-4 py-3 sm:px-5 sm:py-4 ring-1 ring-white/20 shadow-lg shrink-0">
                    <p className="text-xs sm:text-sm md:text-base leading-relaxed text-white/95">
                      {item.desc}
                    </p>
                  </div>
                  <Link
                    href={item.link}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex justify-end w-full shrink-0"
                  >
                    <motion.span
                      className="group inline-flex items-center gap-2 px-4 py-3 sm:px-6 sm:py-4 md:px-8 md:py-4 lg:px-10 lg:py-5 bg-white/95 backdrop-blur-sm text-gray-800 font-semibold rounded-xl shadow-lg ring-1 ring-black/5 hover:shadow-xl hover:bg-white transition-all duration-300 cursor-pointer"
                      whileHover={{ scale: 1.02, y: -2 }}
                      whileTap={{ scale: 0.98 }}
                    >
                      <span className="text-base md:text-lg">See Demo</span>
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20"
                        fill="currentColor"
                        className="w-5 h-5 transition-transform group-hover:translate-x-1 group-hover:-translate-y-0.5"
                        aria-hidden
                      >
                        <path
                          fillRule="evenodd"
                          d="M4.25 5.5a.75.75 0 00-.75.75v8.5c0 .414.336.75.75.75h8.5a.75.75 0 00.75-.75v-4a.75.75 0 011.5 0v4A2.25 2.25 0 0112.75 17h-8.5A2.25 2.25 0 012 14.75v-8.5A2.25 2.25 0 014.25 4h5a.75.75 0 010 1.5h-5z"
                          clipRule="evenodd"
                        />
                        <path
                          fillRule="evenodd"
                          d="M6.194 12.753a.75.75 0 001.06.053L16.5 4.44v2.81a.75.75 0 001.5 0v-4.5a.75.75 0 00-.75-.75h-4.5a.75.75 0 000 1.5h2.553l-9.056 8.194a.75.75 0 00-.053 1.06z"
                          clipRule="evenodd"
                        />
                      </svg>
                    </motion.span>
                  </Link>
                </div>
              </div>
            ))}
          </motion.div>
        </div>
      </div>
      <div className="w-screen h-screen flex flex-col gap-16 items-center justify-center text-center">
        <h1 className="text-8xl">Do you have a project?</h1>
        <div className="relative">
          <motion.svg
            animate={{ rotate: 360 }}
            transition={{ duration: 8, ease: "linear", repeat: Infinity }}
            viewBox="0 0 300 300"
            className="w-64 h-64 md:w-[500px] md:h-[500px] "
          >
            <defs>
              <path
                id="circlePath"
                d="M 150, 150 m -60, 0 a 60,60 0 0,1 120,0 a 60,60 0 0,1 -120,0 "
              />
            </defs>
            <text fill="#000">
              <textPath xlinkHref="#circlePath" className="text-xl">
                Front-end Developer and FullStack Developer
              </textPath>
            </text>
          </motion.svg>
          <Link
            href="/contact"
            className="w-16 h-16 md:w-28 md:h-28 absolute top-0 left-0 right-0 bottom-0 m-auto bg-black text-white rounded-full flex items-center justify-center"
          >
            Hire Me
          </Link>
        </div>
      </div>
    </motion.div>
  );
};

export default PortfolioPage;